%% =========================
% Setup: load rezProjStats
% =========================
load(compatiblepath("Z:\Rodent Data\dualImaging_parkj\collectData\glmTdrAxesProjRezCollection_031826.mat"), ...
    "rezProjStats") % "anchorLOO"

%% =========================
% Setup: IDs, colormaps, time, axis groups
% =========================
mIdC = cellfun(@(a) a.mouseId, rezProjStats.perMouse, 'UniformOutput', false);

% Group split
fastC = {'m1044', 'm1045', 'm1092', 'm1094'};
slowC = {'m1048', 'm1049', 'm1613', 'm1859', 'm1873'};

fastId = find(ismember(mIdC, fastC));
slowId = find(ismember(mIdC, slowC));


rb   = redwhiteblue_wide(256, 3);
gray = grayscale_nonlinear(256, 'gamma', 2.5);

timeX     = rezProjStats.perMouse{1,1}.time;
axisNames = rezProjStats.perMouse{1,1}.axes.names;

% Axis selectors
goToneOnI    = startsWith(axisNames, "GoToneOn")';
goToneOffI   = startsWith(axisNames, "ToneOffGo")';
nogoToneOnI  = startsWith(axisNames, "NoGoToneOn")';
nogoToneOffI = startsWith(axisNames, "ToneOffNoGo")';

goAxisI   = logical(goToneOnI   + goToneOffI);
nogoAxisI = logical(nogoToneOnI + nogoToneOffI);

%% =========================
% Descriptive statistics extracted from rezProjStats
% =========================
% % --- Spearman
% muGo_spearmanC = cellfun(@(a) a.stats.spearman.muGo.stat, rezProjStats.perMouse(:,1), 'UniformOutput', false);
% muGo_spearmanSigC = cellfun(@(a) round(a.stats.spearman.muGo.p1_cluster, 2) <= 0.051, rezProjStats.perMouse(:,1), 'UniformOutput', false);
% 
% muNoGo_spearmanC = cellfun(@(a) a.stats.spearman.muNoGo.stat, rezProjStats.perMouse(:,1), 'UniformOutput', false);
% muNoGo_spearmanSigC = cellfun(@(a) round(a.stats.spearman.muNoGo.p1_cluster, 2) <= 0.051, rezProjStats.perMouse(:,1), 'UniformOutput', false);

% --- Slope (standardized)
muGo_slopeC = cellfun(@(a) a.stats.slope.muGo.statSD, rezProjStats.perMouse(:,1), 'UniformOutput', false);
muGo_slopeSigC = cellfun(@(a) round(a.stats.slope.muGo.p1_cluster, 2) <= 0.051, rezProjStats.perMouse(:,1), 'UniformOutput', false);

muNoGo_slopeC = cellfun(@(a) a.stats.slope.muNoGo.statSD, rezProjStats.perMouse(:,1), 'UniformOutput', false);
muNoGo_slopeSigC = cellfun(@(a) round(a.stats.slope.muNoGo.p1_cluster, 2) <= 0.051, rezProjStats.perMouse(:,1), 'UniformOutput', false);

%% =========================
% Visualization: stacked heatmaps
% Symmetric within-type and cross-type projections
% =========================
% --- NoGo trial activity projected onto NoGo-related axes
[~, muNoGo_slope_projNoGoAxis] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, 'colormap', rb, 'axisI', nogoAxisI, 'header', mIdC, ...
    'clims', [-1 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', false, ...
    'figSaveLogic', true, 'figName', "muNoGo_slope_projNoGoAxis_sigSlopes");

[~, muNoGo_absSlope_projNoGoAxis] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, 'colormap', gray, 'axisI', nogoAxisI, 'header', mIdC, ...
    'clims', [0 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', true);

% --- NoGo trial activity projected onto Go-related axes
[~, muNoGo_slope_projGoAxis] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, 'colormap', rb, 'axisI', goAxisI, 'header', mIdC, ...
    'clims', [-1 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', false, ...
    'figSaveLogic', true, 'figName', "muNoGo_slope_projGoAxis");

[~, muNoGo_absSlope_projGoAxis] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, 'colormap', gray, 'axisI', goAxisI, 'header', mIdC, ...
    'clims', [0 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', true);

% --- Go trial activity projected onto Go-related axes
[~, muGo_slope_projGoAxis] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, 'colormap', rb, 'axisI', goAxisI, 'header', mIdC, ...
    'clims', [-1 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', false, ...
    'figSaveLogic', true, 'figName', "muGo_slope_projGoAxis_sigSlopes");

[~, muGo_absSlope_projGoAxis] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, 'colormap', gray, 'axisI', goAxisI, 'header', mIdC, ...
    'clims', [0 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', muGo_slopeSigC, 'absSlope', true);

% --- Go trial activity projected onto NoGo-related axes
[~, muGo_slope_projNoGoAxis] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, 'colormap', rb, 'axisI', nogoAxisI, 'header', mIdC, ...
    'clims', [-1 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', false, ...
    'figSaveLogic', true, 'figName', "muGo_slope_projNoGoAxis");

[~, muGo_absSlope_projNoGoAxis] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, 'colormap', gray, 'axisI', nogoAxisI, 'header', mIdC, ...
    'clims', [0 1], 'titleStr', '', 'showColorbar', true, ...
    'sigMask', [], 'absSlope', true);

%% =========================
% Group extraction helper pattern
% For each projection set, generate:
%   mean_*  : per-mouse mean across selected axes
%   abs variants
% =========================
%% --- 1) NoGo -> NoGo axis
mean_muNoGo_slope_projNoGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muNoGo_slope_projNoGoAxis(fastId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_projNoGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muNoGo_slope_projNoGoAxis(fastId,1), 'UniformOutput', false)));

mean_muNoGo_slope_projNoGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muNoGo_slope_projNoGoAxis(slowId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_projNoGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muNoGo_slope_projNoGoAxis(slowId,1), 'UniformOutput', false)));

%% --- 2) NoGo -> Go axis
mean_muNoGo_slope_projGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muNoGo_slope_projGoAxis(fastId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_projGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muNoGo_slope_projGoAxis(fastId,1), 'UniformOutput', false)));

mean_muNoGo_slope_projGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muNoGo_slope_projGoAxis(slowId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_projGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muNoGo_slope_projGoAxis(slowId,1), 'UniformOutput', false)));

%% --- 3) Go -> Go axis
mean_muGo_slope_projGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muGo_slope_projGoAxis(fastId,1), 'UniformOutput', false)));

mean_muGo_absSlope_projGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muGo_slope_projGoAxis(fastId,1), 'UniformOutput', false)));

mean_muGo_slope_projGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muGo_slope_projGoAxis(slowId,1), 'UniformOutput', false)));

mean_muGo_absSlope_projGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muGo_slope_projGoAxis(slowId,1), 'UniformOutput', false)));

%% --- 4) Go -> NoGo axis
mean_muGo_slope_projNoGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muGo_slope_projNoGoAxis(fastId,1), 'UniformOutput', false)));

mean_muGo_absSlope_projNoGoAxis_fasts = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muGo_slope_projNoGoAxis(fastId,1), 'UniformOutput', false)));

mean_muGo_slope_projNoGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 'omitnan'), ...
    muGo_slope_projNoGoAxis(slowId,1), 'UniformOutput', false)));

mean_muGo_absSlope_projNoGoAxis_slows = ...
    double(cell2mat(cellfun(@(a) mean(abs(a), 'omitnan'), ...
    muGo_slope_projNoGoAxis(slowId,1), 'UniformOutput', false)));

%% =========================
% Downsample from 50 ms to 100 ms bins
% (Mean-across-axes data only)
% =========================
% --- 1) NoGo -> NoGo axis
[mean_muNoGo_absSlope_projNoGoAxis_fasts_ds, timeX_ds] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_projNoGoAxis_fasts, timeX, 0.1);
[mean_muNoGo_absSlope_projNoGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_projNoGoAxis_slows, timeX, 0.1);

[mean_muNoGo_slope_projNoGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_projNoGoAxis_fasts, timeX, 0.1);
[mean_muNoGo_slope_projNoGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_projNoGoAxis_slows, timeX, 0.1);

% --- 2) NoGo -> Go axis
[mean_muNoGo_absSlope_projGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_projGoAxis_fasts, timeX, 0.1);
[mean_muNoGo_absSlope_projGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_projGoAxis_slows, timeX, 0.1);

[mean_muNoGo_slope_projGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_projGoAxis_fasts, timeX, 0.1);
[mean_muNoGo_slope_projGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_projGoAxis_slows, timeX, 0.1);

% --- 3) Go -> Go axis
[mean_muGo_absSlope_projGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_projGoAxis_fasts, timeX, 0.1);
[mean_muGo_absSlope_projGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_projGoAxis_slows, timeX, 0.1);

[mean_muGo_slope_projGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_projGoAxis_fasts, timeX, 0.1);
[mean_muGo_slope_projGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_projGoAxis_slows, timeX, 0.1);

% --- 4) Go -> NoGo axis
[mean_muGo_absSlope_projNoGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_projNoGoAxis_fasts, timeX, 0.1);
[mean_muGo_absSlope_projNoGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_projNoGoAxis_slows, timeX, 0.1);

[mean_muGo_slope_projNoGoAxis_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_projNoGoAxis_fasts, timeX, 0.1);
[mean_muGo_slope_projNoGoAxis_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_projNoGoAxis_slows, timeX, 0.1);

%% =========================
% Group-by-time RM-ANOVA
% (Mean-across-axes data only)
% =========================
% --- 1) NoGo -> NoGo axis
stats.mean_muNoGo_absSlope_projNoGoAxis = runGroupTimeRMANOVA( ...
    mean_muNoGo_absSlope_projNoGoAxis_fasts_ds, mean_muNoGo_absSlope_projNoGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muNoGo abs slope projected onto NoGo axis');

stats.mean_muNoGo_slope_projNoGoAxis = runGroupTimeRMANOVA( ...
    mean_muNoGo_slope_projNoGoAxis_fasts_ds, mean_muNoGo_slope_projNoGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, 'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muNoGo signed slope projected onto NoGo axis');

% --- 2) NoGo -> Go axis
stats.mean_muNoGo_absSlope_projGoAxis = runGroupTimeRMANOVA( ...
    mean_muNoGo_absSlope_projGoAxis_fasts_ds, mean_muNoGo_absSlope_projGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muNoGo abs slope projected onto Go axis');

stats.mean_muNoGo_slope_projGoAxis = runGroupTimeRMANOVA( ...
    mean_muNoGo_slope_projGoAxis_fasts_ds, mean_muNoGo_slope_projGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muNoGo signed slope projected onto Go axis');

% --- 3) Go -> Go axis
stats.mean_muGo_absSlope_projGoAxis = runGroupTimeRMANOVA( ...
    mean_muGo_absSlope_projGoAxis_fasts_ds, mean_muGo_absSlope_projGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, 'timeBounds', [0 2], ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muGo abs slope projected onto Go axis');

stats.mean_muGo_slope_projGoAxis = runGroupTimeRMANOVA( ...
    mean_muGo_slope_projGoAxis_fasts_ds, mean_muGo_slope_projGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, 'timeBounds', [0 2], ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muGo signed slope projected onto Go axis');

% --- 4) Go -> NoGo axis
stats.mean_muGo_absSlope_projNoGoAxis = runGroupTimeRMANOVA( ...
    mean_muGo_absSlope_projNoGoAxis_fasts_ds, mean_muGo_absSlope_projNoGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muGo abs slope projected onto NoGo axis');

stats.mean_muGo_slope_projNoGoAxis = runGroupTimeRMANOVA( ...
    mean_muGo_slope_projNoGoAxis_fasts_ds, mean_muGo_slope_projNoGoAxis_slows_ds, ...
    'groupNames', {'fast','slow'}, 'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', 'alpha', 0.05, 'doPlot', true, ...
    'plotTitle', 'muGo signed slope projected onto NoGo axis');

save(compatiblepath("Z:\Rodent Data\dualImaging_parkj\collectData\glmTdrAxesProjRezCollection_031826.mat"), ...
    "stats", "-append") % "anchorLOO"

%% =========================
% Mean ± SEM shaded plots: Fast vs Slow
% Using downsampled mean-across-axes trajectories
% =========================

% Assumes colorMatFS is already defined, e.g.
colorMatFS = [157, 0, 255; 80, 200, 120]./255; 

%% --- 1) NoGo -> NoGo axis
[avg_mean_muNoGo_slope_projNoGoAxis_fasts, ~, sem_mean_muNoGo_slope_projNoGoAxis_fasts] = ...
    meanstdsem(mean_muNoGo_slope_projNoGoAxis_fasts_ds);
[avg_mean_muNoGo_slope_projNoGoAxis_slows, ~, sem_mean_muNoGo_slope_projNoGoAxis_slows] = ...
    meanstdsem(mean_muNoGo_slope_projNoGoAxis_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_slope_projNoGoAxis_fasts; avg_mean_muNoGo_slope_projNoGoAxis_slows], ...
    [sem_mean_muNoGo_slope_projNoGoAxis_fasts; sem_mean_muNoGo_slope_projNoGoAxis_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, 'LineWidth', 2, 'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', 'YLabel', 'Slope', ...
    'TitleStr', '', 'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, 'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', "Z:\Rodent Data\dualImaging_parkj\collectFigure\motifTDR\glmTDR\glmTDR_across_session_slope", ...
    'figName', "meanSem_slope_muNoGo_projNoGoAxis_FastSlow");

%% --- 2) NoGo -> Go axis
[avg_mean_muNoGo_slope_projGoAxis_fasts, ~, sem_mean_muNoGo_slope_projGoAxis_fasts] = ...
    meanstdsem(mean_muNoGo_slope_projGoAxis_fasts_ds);
[avg_mean_muNoGo_slope_projGoAxis_slows, ~, sem_mean_muNoGo_slope_projGoAxis_slows] = ...
    meanstdsem(mean_muNoGo_slope_projGoAxis_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_slope_projGoAxis_fasts; avg_mean_muNoGo_slope_projGoAxis_slows], ...
    [sem_mean_muNoGo_slope_projGoAxis_fasts; sem_mean_muNoGo_slope_projGoAxis_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, 'LineWidth', 2, 'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', 'YLabel', 'Slope', ...
    'TitleStr', '', 'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, 'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', "Z:\Rodent Data\dualImaging_parkj\collectFigure\motifTDR\glmTDR\glmTDR_across_session_slope", ...
    'figName', "meanSem_slope_muNoGo_projGoAxis_FastSlow");

%% --- 3) Go -> Go axis
[avg_mean_muGo_slope_projGoAxis_fasts, ~, sem_mean_muGo_slope_projGoAxis_fasts] = ...
    meanstdsem(mean_muGo_slope_projGoAxis_fasts_ds);
[avg_mean_muGo_slope_projGoAxis_slows, ~, sem_mean_muGo_slope_projGoAxis_slows] = ...
    meanstdsem(mean_muGo_slope_projGoAxis_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_slope_projGoAxis_fasts; avg_mean_muGo_slope_projGoAxis_slows], ...
    [sem_mean_muGo_slope_projGoAxis_fasts; sem_mean_muGo_slope_projGoAxis_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, 'LineWidth', 2, 'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', 'YLabel', 'Slope', ...
    'TitleStr', '', 'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, 'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', "Z:\Rodent Data\dualImaging_parkj\collectFigure\motifTDR\glmTDR\glmTDR_across_session_slope", ...
    'figName', "meanSem_slope_muGo_projGoAxis_FastSlow");

%% --- 4) Go -> NoGo axis
[avg_mean_muGo_slope_projNoGoAxis_fasts, ~, sem_mean_muGo_slope_projNoGoAxis_fasts] = ...
    meanstdsem(mean_muGo_slope_projNoGoAxis_fasts_ds);
[avg_mean_muGo_slope_projNoGoAxis_slows, ~, sem_mean_muGo_slope_projNoGoAxis_slows] = ...
    meanstdsem(mean_muGo_slope_projNoGoAxis_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_slope_projNoGoAxis_fasts; avg_mean_muGo_slope_projNoGoAxis_slows], ...
    [sem_mean_muGo_slope_projNoGoAxis_fasts; sem_mean_muGo_slope_projNoGoAxis_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, 'LineWidth', 2, 'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', 'YLabel', 'Slope', ...
    'TitleStr', '', 'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, 'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', "Z:\Rodent Data\dualImaging_parkj\collectFigure\motifTDR\glmTDR\glmTDR_across_session_slope", ...
    'figName', "meanSem_slope_muGo_projNoGoAxis_FastSlow");

%% =========================
% Local helper
% =========================
function idx = axisNameContains(axisNames, keyword)
% axisNameContains
% Returns logical index of axis names containing the keyword.
%
% INPUT
%   axisNames : cell array of strings
%   keyword   : string or char
%
% OUTPUT
%   idx       : logical index vector

    axisNames = string(axisNames);
    keyword   = string(keyword);
    idx = contains(axisNames, keyword);
end