%% ========================================================================
% GLM-TDR across-session slope analysis
%
% This version uses clearer naming:
%   onGoAxes    = rows/axes whose names are Go-related
%   onNoGoAxes  = rows/axes whose names are NoGo-related
%
% Important:
%   The projection already happened upstream when rezProjStats was computed.
%   Here we are plotting slope matrices and selecting rows/axes.
%
% Included statistics:
%   1) muNoGo slopes
%   2) muGo slopes
%   3) diff slopes
%
% diff convention:
%   Stored diff = muGo - muNoGo
%
% For Go axes:
%   signed diff is kept as Go - NoGo
%
% For NoGo axes:
%   signed diff is sign-flipped to NoGo - Go
%
% This makes positive signed diff consistently mean:
%   condition-preferred separation increases with learning.
%% ========================================================================

%% =========================
% Setup: load rezProjStats
% =========================
load(compatiblepath("Z:\Rodent Data\dualImaging_parkj\collectData\glmTdrAxesProjRezCollection_redCal_L10K10_070626.mat"), ...
    "rezProjStats") % "anchorLOO"

%% =========================
% Setup: IDs, colormaps, time, axis groups
% =========================
mIdC = cellfun(@(a) a.mouseId, rezProjStats.perMouse, 'UniformOutput', false);

% Group split
fastC = {'m1044', 'm1045', 'm1092', 'm1094'};
slowC = {'m1048', 'm1049', 'm1613', 'm1859', 'm1873'};

fastId = find(ismember(mIdC, fastC));
slowId = find(ismember(mIdC, slowC));

rb   = redwhiteblue_wide(256, 3);
gray = grayscale_nonlinear(256, 'gamma', 2.5);

timeX     = rezProjStats.perMouse{1,1}.time;
axisNames = rezProjStats.perMouse{1,1}.axes.names;

% Axis selectors
goToneOnI    = startsWith(axisNames, "GoToneOn")';
goToneOffI   = startsWith(axisNames, "ToneOffGo")';
nogoToneOnI  = startsWith(axisNames, "NoGoToneOn")';
nogoToneOffI = startsWith(axisNames, "ToneOffNoGo")';

goAxisI   = logical(goToneOnI   + goToneOffI);
nogoAxisI = logical(nogoToneOnI + nogoToneOffI);

figSaveDirSlope = "Z:\Rodent Data\dualImaging_parkj\collectFigure\motifTDR\glmTDR\glmTDR_across_session_slope";

%% =========================
% Descriptive statistics extracted from rezProjStats
% =========================

% --- Slope, standardized effect size
muGo_slopeC = cellfun(@(a) a.stats.slope.muGo.statSD, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

muGo_slopeSigC = cellfun(@(a) round(a.stats.slope.muGo.p1_cluster, 2) <= 0.051, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

muNoGo_slopeC = cellfun(@(a) a.stats.slope.muNoGo.statSD, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

muNoGo_slopeSigC = cellfun(@(a) round(a.stats.slope.muNoGo.p1_cluster, 2) <= 0.051, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

% --- diff slope
% Stored convention:
%   diff = muGo - muNoGo
diff_slopeC = cellfun(@(a) a.stats.slope.diff.statSD, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

diff_slopeSigC = cellfun(@(a) round(a.stats.slope.diff.p1_cluster, 2) <= 0.051, ...
    rezProjStats.perMouse(:,1), 'UniformOutput', false);

% Sign-normalized version for NoGo-axis plots:
%   -diff = muNoGo - muGo
diff_slopeC_NoGoPositive = cellfun(@(a) -a, diff_slopeC, 'UniformOutput', false);

%% =========================
% Visualization: stacked heatmaps of slope matrices
%
% These are NOT new projections.
% Each cell is an [axis x time] slope matrix.
% axisI simply selects Go-related or NoGo-related rows/axes.
%% =========================

%% --- 1) muNoGo slopes on NoGo-related axes
[~, muNoGo_slope_onNoGoAxes] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'muNoGo learning slopes on NoGo-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muNoGo_slope_onNoGoAxes");

[~, muNoGo_absSlope_onNoGoAxes] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'titleStr', '|muNoGo learning slope| on NoGo-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muNoGo_absSlope_onNoGoAxes");

%% --- 2) muNoGo slopes on Go-related axes
[~, muNoGo_slope_onGoAxes] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'muNoGo learning slopes on Go-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muNoGo_slope_onGoAxes");

[~, muNoGo_absSlope_onGoAxes] = plotCellImagescStack(muNoGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'titleStr', '|muNoGo learning slope| on Go-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muNoGo_absSlope_onGoAxes");

%% --- 3) muGo slopes on Go-related axes
[~, muGo_slope_onGoAxes] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'muGo learning slopes on Go-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muGo_slope_onGoAxes");

[~, muGo_absSlope_onGoAxes] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'sigMask', [], ...
    'titleStr', '|muGo learning slope| on Go-related axes', ...
    'showColorbar', true, ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muGo_absSlope_onGoAxes");

%% --- 4) muGo slopes on NoGo-related axes
[~, muGo_slope_onNoGoAxes] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'muGo learning slopes on NoGo-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muGo_slope_onNoGoAxes");

[~, muGo_absSlope_onNoGoAxes] = plotCellImagescStack(muGo_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'titleStr', '|muGo learning slope| on NoGo-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "muGo_absSlope_onNoGoAxes");

%% --- 5) diff slopes on Go-related axes
% Stored convention: diff = Go - NoGo.
% For Go axes, keep this sign.
[~, diff_slope_onGoAxes] = plotCellImagescStack(diff_slopeC, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'diff learning slopes on Go-related axes: Go - NoGo', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "diff_slope_onGoAxes_GoMinusNoGo");

[~, diff_absSlope_onGoAxes] = plotCellImagescStack(diff_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', goAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'titleStr', '|diff learning slope| on Go-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "diff_absSlope_onGoAxes");

%% --- 6) diff slopes on NoGo-related axes
% Stored convention: diff = Go - NoGo.
% For NoGo axes, flip sign so positive means NoGo - Go.
[~, diff_slope_onNoGoAxes] = plotCellImagescStack(diff_slopeC_NoGoPositive, ...
    'timeX', timeX, ...
    'colormap', rb, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [-1 1], ...
    'titleStr', 'diff learning slopes on NoGo-related axes: NoGo - Go', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', false, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "diff_slope_onNoGoAxes_NoGoMinusGo");

[~, diff_absSlope_onNoGoAxes] = plotCellImagescStack(diff_slopeC, ...
    'timeX', timeX, ...
    'colormap', gray, ...
    'axisI', nogoAxisI, ...
    'header', mIdC, ...
    'clims', [0 1], ...
    'titleStr', '|diff learning slope| on NoGo-related axes', ...
    'showColorbar', true, ...
    'sigMask', [], ...
    'absSlope', true, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "diff_absSlope_onNoGoAxes");

%% =========================
% Group extraction helper pattern
%
% Each *_onGoAxes or *_onNoGoAxes cell contains:
%   [selectedAxes x time]
%
% Here we average across selected axes for each mouse:
%   output = [mouse x time]
%% =========================

%% --- 1) muNoGo slopes on NoGo-related axes
mean_muNoGo_slope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_slope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_absSlope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_muNoGo_slope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_slope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_absSlope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

%% --- 2) muNoGo slopes on Go-related axes
mean_muNoGo_slope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_slope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_absSlope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_muNoGo_slope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_slope_onGoAxes(slowId,1), 'UniformOutput', false)));

mean_muNoGo_absSlope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muNoGo_absSlope_onGoAxes(slowId,1), 'UniformOutput', false)));

%% --- 3) muGo slopes on Go-related axes
mean_muGo_slope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_slope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_muGo_absSlope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_absSlope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_muGo_slope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_slope_onGoAxes(slowId,1), 'UniformOutput', false)));

mean_muGo_absSlope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_absSlope_onGoAxes(slowId,1), 'UniformOutput', false)));

%% --- 4) muGo slopes on NoGo-related axes
mean_muGo_slope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_slope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_muGo_absSlope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_absSlope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_muGo_slope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_slope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

mean_muGo_absSlope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    muGo_absSlope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

%% --- 5) diff slopes on Go-related axes
% Convention: Go - NoGo
mean_diff_slope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_slope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_diff_absSlope_onGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_absSlope_onGoAxes(fastId,1), 'UniformOutput', false)));

mean_diff_slope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_slope_onGoAxes(slowId,1), 'UniformOutput', false)));

mean_diff_absSlope_onGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_absSlope_onGoAxes(slowId,1), 'UniformOutput', false)));

%% --- 6) diff slopes on NoGo-related axes
% Convention: NoGo - Go after sign flip
mean_diff_slope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_slope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_diff_absSlope_onNoGoAxes_fasts = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_absSlope_onNoGoAxes(fastId,1), 'UniformOutput', false)));

mean_diff_slope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_slope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

mean_diff_absSlope_onNoGoAxes_slows = ...
    double(cell2mat(cellfun(@(a) mean(a, 1, 'omitnan'), ...
    diff_absSlope_onNoGoAxes(slowId,1), 'UniformOutput', false)));

%% =========================
% Downsample from 50 ms to 100 ms bins
% Mean-across-axes data only
%  =========================

%% --- 1) muNoGo slopes on NoGo-related axes
[mean_muNoGo_absSlope_onNoGoAxes_fasts_ds, timeX_ds] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_onNoGoAxes_fasts, timeX, 0.1);
[mean_muNoGo_absSlope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_onNoGoAxes_slows, timeX, 0.1);

[mean_muNoGo_slope_onNoGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_onNoGoAxes_fasts, timeX, 0.1);
[mean_muNoGo_slope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_onNoGoAxes_slows, timeX, 0.1);

%% --- 2) muNoGo slopes on Go-related axes
[mean_muNoGo_absSlope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_onGoAxes_fasts, timeX, 0.1);
[mean_muNoGo_absSlope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_absSlope_onGoAxes_slows, timeX, 0.1);

[mean_muNoGo_slope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_onGoAxes_fasts, timeX, 0.1);
[mean_muNoGo_slope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muNoGo_slope_onGoAxes_slows, timeX, 0.1);

%% --- 3) muGo slopes on Go-related axes
[mean_muGo_absSlope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_onGoAxes_fasts, timeX, 0.1);
[mean_muGo_absSlope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_onGoAxes_slows, timeX, 0.1);

[mean_muGo_slope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_onGoAxes_fasts, timeX, 0.1);
[mean_muGo_slope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_onGoAxes_slows, timeX, 0.1);

%% --- 4) muGo slopes on NoGo-related axes
[mean_muGo_absSlope_onNoGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_onNoGoAxes_fasts, timeX, 0.1);
[mean_muGo_absSlope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_absSlope_onNoGoAxes_slows, timeX, 0.1);

[mean_muGo_slope_onNoGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_onNoGoAxes_fasts, timeX, 0.1);
[mean_muGo_slope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_muGo_slope_onNoGoAxes_slows, timeX, 0.1);

%% --- 5) diff slopes on Go-related axes
[mean_diff_absSlope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_absSlope_onGoAxes_fasts, timeX, 0.1);
[mean_diff_absSlope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_absSlope_onGoAxes_slows, timeX, 0.1);

[mean_diff_slope_onGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_slope_onGoAxes_fasts, timeX, 0.1);
[mean_diff_slope_onGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_slope_onGoAxes_slows, timeX, 0.1);

%% --- 6) diff slopes on NoGo-related axes
[mean_diff_absSlope_onNoGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_absSlope_onNoGoAxes_fasts, timeX, 0.1);
[mean_diff_absSlope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_absSlope_onNoGoAxes_slows, timeX, 0.1);

[mean_diff_slope_onNoGoAxes_fasts_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_slope_onNoGoAxes_fasts, timeX, 0.1);
[mean_diff_slope_onNoGoAxes_slows_ds, ~] = ...
    downsampleTimeBinsMean(mean_diff_slope_onNoGoAxes_slows, timeX, 0.1);

%% =========================
% Group-by-time RM-ANOVA
% Mean-across-axes data only
%% =========================

%% --- 1) muNoGo slopes on NoGo-related axes
stats.mean_muNoGo_absSlope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_muNoGo_absSlope_onNoGoAxes_fasts_ds, mean_muNoGo_absSlope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muNoGo abs slope on NoGo-related axes');

stats.mean_muNoGo_slope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_muNoGo_slope_onNoGoAxes_fasts_ds, mean_muNoGo_slope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muNoGo signed slope on NoGo-related axes');

%% --- 2) muNoGo slopes on Go-related axes
stats.mean_muNoGo_absSlope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_muNoGo_absSlope_onGoAxes_fasts_ds, mean_muNoGo_absSlope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muNoGo abs slope on Go-related axes');

stats.mean_muNoGo_slope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_muNoGo_slope_onGoAxes_fasts_ds, mean_muNoGo_slope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muNoGo signed slope on Go-related axes');

%% --- 3) muGo slopes on Go-related axes
stats.mean_muGo_absSlope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_muGo_absSlope_onGoAxes_fasts_ds, mean_muGo_absSlope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 2], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muGo abs slope on Go-related axes');

stats.mean_muGo_slope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_muGo_slope_onGoAxes_fasts_ds, mean_muGo_slope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 2], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muGo signed slope on Go-related axes');

%% --- 4) muGo slopes on NoGo-related axes
stats.mean_muGo_absSlope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_muGo_absSlope_onNoGoAxes_fasts_ds, mean_muGo_absSlope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muGo abs slope on NoGo-related axes');

stats.mean_muGo_slope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_muGo_slope_onNoGoAxes_fasts_ds, mean_muGo_slope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'muGo signed slope on NoGo-related axes');

%% --- 5) diff slopes on Go-related axes
stats.mean_diff_absSlope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_diff_absSlope_onGoAxes_fasts_ds, mean_diff_absSlope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'absolute diff slope on Go-related axes');

stats.mean_diff_slope_onGoAxes = runGroupTimeRMANOVA( ...
    mean_diff_slope_onGoAxes_fasts_ds, mean_diff_slope_onGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'diff slope on Go-related axes: Go - NoGo');

%% --- 6) diff slopes on NoGo-related axes
stats.mean_diff_absSlope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_diff_absSlope_onNoGoAxes_fasts_ds, mean_diff_absSlope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'absolute diff slope on NoGo-related axes');

stats.mean_diff_slope_onNoGoAxes = runGroupTimeRMANOVA( ...
    mean_diff_slope_onNoGoAxes_fasts_ds, mean_diff_slope_onNoGoAxes_slows_ds, ...
    'groupNames', {'fast','slow'}, ...
    'timeX', timeX_ds, ...
    'timeBounds', [0 5], ...
    'multcompareMethod', 'fdr', ...
    'alpha', 0.05, ...
    'doPlot', true, ...
    'plotTitle', 'diff slope on NoGo-related axes: NoGo - Go');

%% Save stats
save(compatiblepath("Z:\Rodent Data\dualImaging_parkj\collectData\glmTdrAxesProjRezCollection_redCal_L10K10_070626.mat"), ...
    "stats", "-append")

%% =========================
% Mean ± SEM shaded plots: Fast vs Slow
% Using downsampled mean-across-axes trajectories
%% =========================

colorMatFS = [157, 0, 255; 80, 200, 120]./255;

%% --- 1) muNoGo slopes on NoGo-related axes | signed
[avg_mean_muNoGo_slope_onNoGoAxes_fasts, ~, sem_mean_muNoGo_slope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_muNoGo_slope_onNoGoAxes_fasts_ds);
[avg_mean_muNoGo_slope_onNoGoAxes_slows, ~, sem_mean_muNoGo_slope_onNoGoAxes_slows] = ...
    meanstdsem(mean_muNoGo_slope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_slope_onNoGoAxes_fasts; avg_mean_muNoGo_slope_onNoGoAxes_slows], ...
    [sem_mean_muNoGo_slope_onNoGoAxes_fasts; sem_mean_muNoGo_slope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'ylim', [-0.28 0.32], ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_slope_muNoGo_onNoGoAxes_FastSlow");

%% --- 1) muNoGo slopes on NoGo-related axes | absolute
[avg_mean_muNoGo_absSlope_onNoGoAxes_fasts, ~, sem_mean_muNoGo_absSlope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_muNoGo_absSlope_onNoGoAxes_fasts_ds);
[avg_mean_muNoGo_absSlope_onNoGoAxes_slows, ~, sem_mean_muNoGo_absSlope_onNoGoAxes_slows] = ...
    meanstdsem(mean_muNoGo_absSlope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_absSlope_onNoGoAxes_fasts; avg_mean_muNoGo_absSlope_onNoGoAxes_slows], ...
    [sem_mean_muNoGo_absSlope_onNoGoAxes_fasts; sem_mean_muNoGo_absSlope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absSlope_muNoGo_onNoGoAxes_FastSlow");

%% --- 2) muNoGo slopes on Go-related axes | signed
[avg_mean_muNoGo_slope_onGoAxes_fasts, ~, sem_mean_muNoGo_slope_onGoAxes_fasts] = ...
    meanstdsem(mean_muNoGo_slope_onGoAxes_fasts_ds);
[avg_mean_muNoGo_slope_onGoAxes_slows, ~, sem_mean_muNoGo_slope_onGoAxes_slows] = ...
    meanstdsem(mean_muNoGo_slope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_slope_onGoAxes_fasts; avg_mean_muNoGo_slope_onGoAxes_slows], ...
    [sem_mean_muNoGo_slope_onGoAxes_fasts; sem_mean_muNoGo_slope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_slope_muNoGo_onGoAxes_FastSlow");

%% --- 2) muNoGo slopes on Go-related axes | absolute
[avg_mean_muNoGo_absSlope_onGoAxes_fasts, ~, sem_mean_muNoGo_absSlope_onGoAxes_fasts] = ...
    meanstdsem(mean_muNoGo_absSlope_onGoAxes_fasts_ds);
[avg_mean_muNoGo_absSlope_onGoAxes_slows, ~, sem_mean_muNoGo_absSlope_onGoAxes_slows] = ...
    meanstdsem(mean_muNoGo_absSlope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muNoGo_absSlope_onGoAxes_fasts; avg_mean_muNoGo_absSlope_onGoAxes_slows], ...
    [sem_mean_muNoGo_absSlope_onGoAxes_fasts; sem_mean_muNoGo_absSlope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absSlope_muNoGo_onGoAxes_FastSlow");

%% --- 3) muGo slopes on Go-related axes | signed
[avg_mean_muGo_slope_onGoAxes_fasts, ~, sem_mean_muGo_slope_onGoAxes_fasts] = ...
    meanstdsem(mean_muGo_slope_onGoAxes_fasts_ds);
[avg_mean_muGo_slope_onGoAxes_slows, ~, sem_mean_muGo_slope_onGoAxes_slows] = ...
    meanstdsem(mean_muGo_slope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_slope_onGoAxes_fasts; avg_mean_muGo_slope_onGoAxes_slows], ...
    [sem_mean_muGo_slope_onGoAxes_fasts; sem_mean_muGo_slope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'ylim', [-0.3 0.4], ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_slope_muGo_onGoAxes_FastSlow");

%% --- 3) muGo slopes on Go-related axes | absolute
[avg_mean_muGo_absSlope_onGoAxes_fasts, ~, sem_mean_muGo_absSlope_onGoAxes_fasts] = ...
    meanstdsem(mean_muGo_absSlope_onGoAxes_fasts_ds);
[avg_mean_muGo_absSlope_onGoAxes_slows, ~, sem_mean_muGo_absSlope_onGoAxes_slows] = ...
    meanstdsem(mean_muGo_absSlope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_absSlope_onGoAxes_fasts; avg_mean_muGo_absSlope_onGoAxes_slows], ...
    [sem_mean_muGo_absSlope_onGoAxes_fasts; sem_mean_muGo_absSlope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absSlope_muGo_onGoAxes_FastSlow");

%% --- 4) muGo slopes on NoGo-related axes | signed
[avg_mean_muGo_slope_onNoGoAxes_fasts, ~, sem_mean_muGo_slope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_muGo_slope_onNoGoAxes_fasts_ds);
[avg_mean_muGo_slope_onNoGoAxes_slows, ~, sem_mean_muGo_slope_onNoGoAxes_slows] = ...
    meanstdsem(mean_muGo_slope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_slope_onNoGoAxes_fasts; avg_mean_muGo_slope_onNoGoAxes_slows], ...
    [sem_mean_muGo_slope_onNoGoAxes_fasts; sem_mean_muGo_slope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_slope_muGo_onNoGoAxes_FastSlow");

%% --- 4) muGo slopes on NoGo-related axes | absolute
[avg_mean_muGo_absSlope_onNoGoAxes_fasts, ~, sem_mean_muGo_absSlope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_muGo_absSlope_onNoGoAxes_fasts_ds);
[avg_mean_muGo_absSlope_onNoGoAxes_slows, ~, sem_mean_muGo_absSlope_onNoGoAxes_slows] = ...
    meanstdsem(mean_muGo_absSlope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_muGo_absSlope_onNoGoAxes_fasts; avg_mean_muGo_absSlope_onNoGoAxes_slows], ...
    [sem_mean_muGo_absSlope_onNoGoAxes_fasts; sem_mean_muGo_absSlope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absSlope_muGo_onNoGoAxes_FastSlow");

%% --- 5) diff slopes on Go-related axes | signed, Go - NoGo
[avg_mean_diff_slope_onGoAxes_fasts, ~, sem_mean_diff_slope_onGoAxes_fasts] = ...
    meanstdsem(mean_diff_slope_onGoAxes_fasts_ds);
[avg_mean_diff_slope_onGoAxes_slows, ~, sem_mean_diff_slope_onGoAxes_slows] = ...
    meanstdsem(mean_diff_slope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_diff_slope_onGoAxes_fasts; avg_mean_diff_slope_onGoAxes_slows], ...
    [sem_mean_diff_slope_onGoAxes_fasts; sem_mean_diff_slope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope: Go - NoGo', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_diffSlope_onGoAxes_GoMinusNoGo_FastSlow");

%% --- 5) diff slopes on Go-related axes | absolute
[avg_mean_diff_absSlope_onGoAxes_fasts, ~, sem_mean_diff_absSlope_onGoAxes_fasts] = ...
    meanstdsem(mean_diff_absSlope_onGoAxes_fasts_ds);
[avg_mean_diff_absSlope_onGoAxes_slows, ~, sem_mean_diff_absSlope_onGoAxes_slows] = ...
    meanstdsem(mean_diff_absSlope_onGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_diff_absSlope_onGoAxes_fasts; avg_mean_diff_absSlope_onGoAxes_slows], ...
    [sem_mean_diff_absSlope_onGoAxes_fasts; sem_mean_diff_absSlope_onGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absDiffSlope_onGoAxes_FastSlow");

%% --- 6) diff slopes on NoGo-related axes | signed, NoGo - Go
[avg_mean_diff_slope_onNoGoAxes_fasts, ~, sem_mean_diff_slope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_diff_slope_onNoGoAxes_fasts_ds);
[avg_mean_diff_slope_onNoGoAxes_slows, ~, sem_mean_diff_slope_onNoGoAxes_slows] = ...
    meanstdsem(mean_diff_slope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_diff_slope_onNoGoAxes_fasts; avg_mean_diff_slope_onNoGoAxes_slows], ...
    [sem_mean_diff_slope_onNoGoAxes_fasts; sem_mean_diff_slope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', 'SD-unit slope: NoGo - Go', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_diffSlope_onNoGoAxes_NoGoMinusGo_FastSlow");

%% --- 6) diff slopes on NoGo-related axes | absolute
[avg_mean_diff_absSlope_onNoGoAxes_fasts, ~, sem_mean_diff_absSlope_onNoGoAxes_fasts] = ...
    meanstdsem(mean_diff_absSlope_onNoGoAxes_fasts_ds);
[avg_mean_diff_absSlope_onNoGoAxes_slows, ~, sem_mean_diff_absSlope_onNoGoAxes_slows] = ...
    meanstdsem(mean_diff_absSlope_onNoGoAxes_slows_ds);

plotMeanSemShadeOverTime( ...
    [avg_mean_diff_absSlope_onNoGoAxes_fasts; avg_mean_diff_absSlope_onNoGoAxes_slows], ...
    [sem_mean_diff_absSlope_onNoGoAxes_fasts; sem_mean_diff_absSlope_onNoGoAxes_slows], ...
    timeX_ds, colorMatFS, ...
    'SmoothN', 3, ...
    'LineWidth', 2, ...
    'FaceAlpha', 0.25, ...
    'XLabel', 'Time (s)', ...
    'YLabel', '|SD-unit slope|', ...
    'TitleStr', '', ...
    'LegendStr', {'Fast', 'Slow'}, ...
    'PlotZeroLine', true, ...
    'ZeroLineX', 0, ...
    'figSaveLogic', true, ...
    'figSaveDir', figSaveDirSlope, ...
    'figName', "meanSem_absDiffSlope_onNoGoAxes_FastSlow");

%% =========================
% Quick sanity checks
%% =========================
fprintf('\nSanity checks:\n');
fprintf('mean_muNoGo_slope_onNoGoAxes_fasts_ds: %d mice x %d time bins\n', ...
    size(mean_muNoGo_slope_onNoGoAxes_fasts_ds,1), size(mean_muNoGo_slope_onNoGoAxes_fasts_ds,2));

fprintf('mean_muGo_slope_onGoAxes_fasts_ds: %d mice x %d time bins\n', ...
    size(mean_muGo_slope_onGoAxes_fasts_ds,1), size(mean_muGo_slope_onGoAxes_fasts_ds,2));

fprintf('mean_diff_slope_onGoAxes_fasts_ds: %d mice x %d time bins\n', ...
    size(mean_diff_slope_onGoAxes_fasts_ds,1), size(mean_diff_slope_onGoAxes_fasts_ds,2));

fprintf('mean_diff_slope_onNoGoAxes_fasts_ds: %d mice x %d time bins\n', ...
    size(mean_diff_slope_onNoGoAxes_fasts_ds,1), size(mean_diff_slope_onNoGoAxes_fasts_ds,2));

%% =========================
% Local helper
%% =========================
function idx = axisNameContains(axisNames, keyword)
% axisNameContains
% Returns logical index of axis names containing the keyword.
%
% INPUT
%   axisNames : cell array of strings
%   keyword   : string or char
%
% OUTPUT
%   idx       : logical index vector

    axisNames = string(axisNames);
    keyword   = string(keyword);
    idx = contains(axisNames, keyword);
end