function name = EntertainingSpockNames()

%max 8 letters
list = {'dYnOmItE','kittens','drudgery',...
    'WasTold2','Alst5pm','sleepy','puppies','PlzWork','Woops',...
    'CptKurk','4lorn','OoAnIdea','cookieHR','SpockHog','Ode2PNI',...
    'malarkey','WasntMe','32btIdea','AGr8tDay','BadIdea','GoodIdea',...
    'mmmBacon','BondJBnd','ndCoffee','PYLONS','Brainzzz','FoodOnA'};

name = list{randi(numel(list),1)};

end
