% Whereabouts
filePath = compatiblepath('Z:\Rodent Data\dualImaging_parkj\m1045_jRGECO_GRABda\m1045_122424\task'); 
filePathDat = compatiblepath(fullfile(filePath, 'Matfiles\m1045_122424_task_day4-8_img_refitChunks_red_dff_combined.mat'));

load(filePathDat, 'tbytDat', 'tbytDat_hAligned')

% Index trials
trI = trialTypeInfoAuditoryGng(filePath); 

% Labels: 1 = Hit (Go), 0 = CR (No-Go)
% y should be Ntrials x 1 (match your tbytDat_hAligned)
% Example params match your request: 100 ms window, 50 ms step, cue 0–2 s, response 2–4.5 s
out = tdr_time_resolved_logistic( ...
    fullfile(filePath, 'Figure'), tbytDat_hAligned, trI.goI, ...
    'Epoch', [0 4], ...
    'Win', 0.100, ...
    'Step', 0.050, ...
    'Lambda', 1, ...
    'SmoothSigma', 0, ...   % set >0 (e.g., 1) to lightly smooth weights across windows
    'DoPlots', true, ...
    'printPlots', true, ...
    'minSD', 1e-3, ...
    'minPerClass', 5);